grocery_management_app/config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    devise_for :users, controllers: { registrations: "registrations"}
    devise_for :grocers, skip: [:sessions, :registrations]
    devise_for :clients, skip: [:sessions, :registrations]

    resources :grocers
    match 'grocer/show_exisiting_order' => 'grocers#show_exisiting_order', via: :get
    resources :items
    match 'item/units_left' => 'items#units_left', via: :get

    resources :clients
    match '/client/client_order_list', to: 'clients#client_order_list', via: :get
    # get 'clients/client_order_list' => 'clients#client_order_list', :as => :client_order_list
    match 'client/grocer_item_list' => 'clients#grocer_item_list', via: :get
    resources :orders
    resources :carts, only: [:create, :edit, :update, :destroy]
    match '/cart/edit', to: 'carts#edit', via: :get


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grocery_management_app/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :grocer
  belongs_to :client
  belongs_to :order_status
  has_many :carts, dependent: :destroy
end

grocery_management_app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_cart_items, only: [:show]

  # GET /orders
  # GET /orders.json
  def index
    if (current_user.user_type == "Grocer")
      @orders = Order.where(:grocer_id => current_user.id)

    else
      @orders = Order.where(:client_id => current_user.id)
    end

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_cart_items
      @carts = @order.carts
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

grocery_management_app/app/helpers/orders_helper.rb
module OrdersHelper
    def get_name order
        if ( current_user.user_type == "Grocer" )
            client = Client.find(order.client_id)
            client.name
        else
            grocer = Grocer.find(order.grocer_id)
            grocer.name
        end
    end

    def delete_order order
         order.destroy
    end

    def get_order_status_name order
        order_status = OrderStatus.find(order.order_status_id)
        order_status.status
    end

    def change_order_status order, id
        p "My order status id = #{id}"
        order.update_attribute(:order_status_id, id)
    end
end

grocery_management_app/app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

grocery_management_app/app/views/orders/_item_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-4">
      <h4><%= item.name %></small></h4>
    </div>
    <div class="col-xs-4">
      <div class="circle"> <%= image_tag item.image.url(:thumb) %> </div>
    </div>
    <div class="col-xs-4">

      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price_per_unit %></span></h4>
        <div class="input-group">
          <p><%= cart.quantity %> <p>
        </div>
        <% if current_user.user_type == "Client" && order.order_status_id == 1%>
            <%id = cart.id%>
          <div >
             <% link_to 'Edit', '/carts/id', :method => :put, class: "btn btn-primary" %>
             <!-- <button class="btn btn-primary" id="edit">Edit</button> -->
              <%= link_to 'Edit', edit_cart_path(cart), class: "btn btn-primary" %>
          </div>
          <div >
              <%= link_to 'Delete', {:controller => "carts", :action => "destroy", :cart => cart, :id => cart.id }, :method => :delete, class: "btn btn-danger" %>
          </div>
        <% end -%>
    </div>

  </div>
</div>

grocery_management_app/app/views/orders/_items_in_order.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @carts.each do |cart| %>
      <%= render "/orders/item_row", item: Item.find(cart.item_id), cart: cart, order: @order %>
    <% end %>
  </div>
</div>
<%= link_to 'Back', root_path, class:"btn btn-primary col-centered"%>

grocery_management_app/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

grocery_management_app/app/views/orders/index.html.erb
<ul class="nav nav-tabs">
  <% if (current_user.user_type == "Client") %>
    <li role="presentation"><%= link_to 'Grocers List', clients_path%></li>
  <%else%>
    <li role="presentation"><%= link_to 'Items List', grocers_path%></li>
  <%end%>
  <li role="presentation" class="active"><%= link_to 'My Orders', orders_path%></li>
</ul>
<br/>
<h1>Orders</h1>
<br/>
<% @orders.each do |order| %>
  <% if !(order.carts == [] || order.carts == nil) %>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h4><%= link_to get_name(order), order%></small></h4>
      </div>
      <div class="col-xs-4">
        <h4><%= get_order_status_name(order) %></h4>
      </div>
      <div class="col-xs-4 text-right">
         <% if ((get_order_status_name(order) == "New") && (current_user.user_type == "Client")) %>
            <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
         <% end%>
      </div>
    <% else
          delete_order(order)
       end %>
    </div>
  </div>
<%end%>

grocery_management_app/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

grocery_management_app/app/views/orders/show.html.erb
<h3 class="text-center">Items in order</h3>
<div id="content">
<%= render "items_in_order" %>
</div>