grocery_management_app/config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    devise_for :users, controllers: { registrations: "registrations"}
    devise_for :grocers, skip: [:sessions, :registrations]
    devise_for :clients, skip: [:sessions, :registrations]

    resources :grocers
    match 'grocer/show_exisiting_order' => 'grocers#show_exisiting_order', via: :get
    resources :items
    match 'item/units_left' => 'items#units_left', via: :get

    resources :clients
    match '/client/client_order_list', to: 'clients#client_order_list', via: :get
    # get 'clients/client_order_list' => 'clients#client_order_list', :as => :client_order_list
    match 'client/grocer_item_list' => 'clients#grocer_item_list', via: :get
    resources :orders
    resources :carts, only: [:create, :edit, :update, :destroy]
    match '/cart/edit', to: 'carts#edit', via: :get


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grocery_management_app/app/models/client.rb
class Client < User
    has_many :orders
end

grocery_management_app/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /clients
  # GET /clients.json
  def index
    @grocers = Grocer.all
    @orders = Client.find(current_user.id).orders
  end

  def grocer_item_list
    # @items = Item.find(params[:grocer_id])
    # render :partial => "/clients/grocer_item_list", :collection => { :orders => @items }
  end

  def client_order_list
    @orders = Client.find(current_user.id).orders
    render :partial => "/clients/client_order_list", :collection => { :orders => @orders }
  end

  def destroy_order
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to client_order_list, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.fetch(:client, {})
    end
end

grocery_management_app/app/helpers/clients_helper.rb
module ClientsHelper
    def refresh_client_orders
        @orders = Client.find(current_user.id).orders
    end
end

grocery_management_app/app/views/clients/_client_order_list.html.erb
<h1>Orders</h1>
<br/>
<% @orders.each do |order| %>
  <% if !(order.carts == [] || order.carts == nil) %>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h4><%= link_to get_name(order), order%></small></h4>
      </div>
      <div class="col-xs-4">
        <h4><%= get_order_status_name(order) %></h4>
      </div>
      <div class="col-xs-4 text-right">
         <% if ((get_order_status_name(order) == "New") && (current_user.user_type == "Client")) %>
            <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
         <% end%>
      </div>
    <% else
          delete_order(order)
       end %>
    </div>
  </div>
<%end%>

grocery_management_app/app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

grocery_management_app/app/views/clients/_grocer_item_list.html.erb
<h3 class="text-center">Items for Sale</h3>
<br/>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @items.each do |item| %>
      <div class="well">
          <div class="row">
            <div class="col-xs-4">
              <h4><%= item.name %></small></h4>
            </div>
            <div class="col-xs-4">
              <div class="circle"> <%= image_tag item.image.url(:thumb) %> </div>
            </div>
            <div class="col-xs-4">
              <%= form_for cart, remote: true do |f| %>
              <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price_per_unit %></span></h4>
               <p class: "text-center "> Units Available: <%= item.units_in_stock%></p>
                <div class="input-group">
                  <%= f.number_field :quantity, value: 1, class: "form-control", max: item.units_in_stock %>
                  <div class="input-group-btn">
                    <%= f.hidden_field :item_id, value: item.id %>
                    <%= f.hidden_field :order_id, value: order.id %>
                    <%= f.submit "Order", class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

grocery_management_app/app/views/clients/_grocers_list.html.erb
<h1>Grocers</h1>
<br/>
<% @grocers.each do |grocer| %>
  <div class="well">

    <div class="row">
      <div class="col-xs-3">
        <div class="circle"> <%= image_tag grocer.dp.url(:thumb) %> </div>
      </div>
      <div class="col-xs-3">
        <h4><%= link_to grocer.name, grocer, onclick: "change_screen()"%></small></h4>
      </div>
      <div class="col-xs-3">
          <h4><%= grocer.phone_no %></small></h4>
      </div>
      <div class="col-xs-3">
          <h4><%= grocer.address %></small></h4>
      </div>
    </div>
  </div>
<%end%>

<script>
function change_screen(){
  console.log("I'm here")
   $('.dynamic').load('/client/grocer_item_list');
}

</script>

grocery_management_app/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

grocery_management_app/app/views/clients/index.html.erb
<div class= "dynamic">
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#home">Grocer List</a></li>
      <li  id="myTab"><a data-toggle="tab" href="#menu1">My Orders</a></li>
    </ul>

    <div class="tab-content">
      <div id="home" class="tab-pane fade in active">
        <%= render 'grocers_list' %>
      </div>
      <div id="menu1" class="tab-pane fade">
      </div>
    </div>
</div>

<script>

$('#myTab').click(function(e){
  console.log("I'm in tab click")
   $('#menu1').load('/client/client_order_list');
})

</script>

grocery_management_app/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

grocery_management_app/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>