grocery_management_app/config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    devise_for :users, controllers: { registrations: "registrations"}
    devise_for :grocers, skip: [:sessions, :registrations]
    devise_for :clients, skip: [:sessions, :registrations]

    resources :grocers
    match 'grocer/show_exisiting_order' => 'grocers#show_exisiting_order', via: :get
    resources :items
    match 'item/units_left' => 'items#units_left', via: :get

    resources :clients
    match '/client/client_order_list', to: 'clients#client_order_list', via: :get
    # get 'clients/client_order_list' => 'clients#client_order_list', :as => :client_order_list
    match 'client/grocer_item_list' => 'clients#grocer_item_list', via: :get
    resources :orders
    resources :carts, only: [:create, :edit, :update, :destroy]
    match '/cart/edit', to: 'carts#edit', via: :get


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grocery_management_app/app/models/grocer.rb
class Grocer < User
    has_many :items
    has_many :orders
    has_many :carts, through: :orders, source: :carts
end

grocery_management_app/app/controllers/grocers_controller.rb
class GrocersController < ApplicationController
  before_action :set_grocer, only: [:show, :edit, :update, :destroy, :show_exisiting_order]
  before_action :set_items, only: [:show, :show_exisiting_order]
  before_action :set_order, only: [:show]
  before_action :set_cart, only: [:show]

  # GET /grocers
  # GET /grocers.json
  def index
    grocer = Grocer.find(current_user.id)
    @items = grocer.items
    @orders = grocer.orders
  end

  # GET /grocers/1
  # GET /grocers/1.json
  def show
  end

  def show_exisiting_order
    @order = Order.find(params[:order_id])
    set_cart
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grocer
      @grocer = Grocer.find(params[:id])
    end

    def set_items
      @items = @grocer.items
    end

    def set_order
      @order = Order.new(:grocer_id => @grocer.id, :client_id => current_user.id, :order_status_id => 1)
      @order.save!
    end

    def set_cart
      @cart = Cart.new(:order_id => @order.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grocer_params
      params.fetch(:grocer, {})
    end
end

grocery_management_app/app/helpers/grocers_helper.rb
module GrocersHelper
    def refresh_orders
        @orders = Grocer.find(current_user.id).orders
    end
end

grocery_management_app/app/views/grocers/_add_item_modal.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
       <%= form_for Item.new, html: { multipart: true } do |f| %>

    <div class="row">
      <div class="field col-md-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control col-md-6" %>
      </div>

      <div class="field col-md-3">
        <%= f.label :price_per_unit %>
        <%= f.text_field :price_per_unit, class: "form-control col-md-6"  %>
      </div>

      <div class="field col-md-3">
        <%= f.label :unit %>
        <%= f.text_field :unit, class: "form-control col-md-6"  %>
      </div>

      <div class="field col-md-3">
        <%= f.label :units_in_stock %>
        <%= f.number_field :units_in_stock, class: "form-control col-md-6"  %>
      </div>
   </div>
   <br/>
    <div class="field col-centered">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
  <br/>
    <div class="actions">
      <%= f.submit "Add Item", class: "btn btn-primary col-centered" %>
    </div>
<% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

grocery_management_app/app/views/grocers/_form.html.erb
<%= form_for(grocer) do |f| %>
  <% if grocer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grocer.errors.count, "error") %> prohibited this grocer from being saved:</h2>

      <ul>
      <% grocer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

grocery_management_app/app/views/grocers/_grocer_items.html.erb
<h1>Items</h1>
<br/>
<% @items.each do |item| %>
  <div class="well">
    <div class="row">
      <div class="col-xs-2">
        <div class="circle"> <%= image_tag item.image.url(:thumb) %> </div>
      </div>
      <div class="col-xs-2">
        <h4><%= link_to item.name, item%></small></h4>
      </div>
      <div class="col-xs-2 ">
        <h4><%= item.units_in_stock%> <%= item.unit %> in stock</small></h4>
      </div>
      <div class="col-xs-2">
        <h4><%= number_to_currency item.price_per_unit  %> per unit</small></h4>
      </div>
      <div class="col-xs-2">
        <!-- <a  data-toggle="modal" data-target="#myModal" class="btn btn-primary" >Add Units to stock</a> -->
        <%= link_to 'Add Units to stock', edit_item_path(item), class: "btn btn-primary" %>
      </div>
      <div class="col-xs-2">
         <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
      </div>
    </div>
  </div>
<%end%>
<%= render 'add_item_modal' %>
<hr/>

<%= link_to 'New Item', new_item_path, class: "btn btn-primary col-centered" %>

grocery_management_app/app/views/grocers/_grocer_orders.html.erb
<h1>Orders</h1>
<br/>
<%refresh_orders%>
<% @orders.each do |order| %>
  <% if !(order.carts == [] || order.carts == nil) %>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h4><%= link_to get_name(order), order%></small></h4>
      </div>
      <div class="col-xs-4">
        <%if (current_user.user_type == "Client")%>
          <h4><%= get_order_status_name(order) %></h4>
        <%else%>
           <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"> <%= get_order_status_name(order) %> <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><a href="#">New</a></li>
              <li><a href="#">Accepted</a></li>
              <li><a href="#">Processing</a></li>
              <li><a href="#">Dispatched</a></li>
            </ul>
          </div>
        <%end%>
      </div>
      <div class="col-xs-4 text-right">
         <% if ((get_order_status_name(order) == "New") && (current_user.user_type == "Client")) %>
            <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
         <% end%>
      </div>
    <% else
          delete_order(order)
       end %>
    </div>
  </div>
<%end%>

grocery_management_app/app/views/grocers/_item_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-4">
      <h4><%= item.name %></small></h4>
    </div>
    <div class="col-xs-4">
      <div class="circle"> <%= image_tag item.image.url(:thumb) %> </div>
    </div>
    <div class="col-xs-4">

      <%= form_for cart, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency item.price_per_unit %></span></h4>
       <p class: "text-center "> Units Available: <%= item.units_in_stock%></p>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", max: item.units_in_stock %>
          <div class="input-group-btn">
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.hidden_field :order_id, value: order.id %>
            <%= f.submit "Order", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

grocery_management_app/app/views/grocers/_products_for_sale.html.erb
<h4 class="order-selected-text"><h4>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @items.each do |item| %>
      <%= render "item_row", item: item, cart: @cart, order: @order %>
    <% end %>
  </div>
</div>
<% link_to "Go Back", root_path, class: "col-centered btn btn-primary" %>

grocery_management_app/app/views/grocers/edit.html.erb
<h1>Editing Grocer</h1>

<%= render 'form', grocer: @grocer %>

<%= link_to 'Show', @grocer %> |
<%= link_to 'Back', grocers_path %>

grocery_management_app/app/views/grocers/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#home">Items List</a></li>
  <li><a data-toggle="tab" href="#menu1">My Orders</a></li>
</ul>

<div class="tab-content">
  <div id="home" class="tab-pane fade in active">
    <%= render 'grocer_items' %>
  </div>
  <div id="menu1" class="tab-pane fade">
    <%= render 'grocer_orders' %>
  </div>
 
</div

grocery_management_app/app/views/grocers/new.html.erb
<h1>New Grocer</h1>

<%= render 'form', grocer: @grocer %>

<%= link_to 'Back', grocers_path %>

grocery_management_app/app/views/grocers/show.html.erb
<h3 class="text-center">Products for Sale</h3>
<div id="products_for_sale_content">
    <%= render "products_for_sale"%>
</div>

<% link_to "Go Back", root_path, class: "col-centered btn btn-primary" %>

grocery_management_app/app/views/grocers/show_exisiting_order.html.erb
<h3 class="text-center">Products for Sale</h3>
<div id="products_for_sale_content">
    <%= render "products_for_sale"%>
</div>

<% link_to "Go Back", root_path, class: "col-centered btn btn-primary" %>